## Ths file symlinked fro: /path/to/covid/nyt/accessory/makefile

default: help

covid:
	cd work/covid/nyt && $(MAKE)

us:
	cd work/covid/nyt  && ./getus.sh

help:
	@echo Some things to try:
	@echo make covid
	@echo make us
	@echo _____________

.PHONY : covid help default
